### ISSUE TITLE
OpenWhisk Plugin Error using deprecated `kong.tools.responses`

### ISSUE THREAD

**Issue by treyau21** [Kong/kong-plugin-openwhisk#11]
The error `module 'kong.tools.responses' not found` occurs on initialization

(See trace attached)

![image](https://user-images.githubusercontent.com/545830/63353734-34e8da00-c331-11e9-86a8-9323dfb25958.png)

It appears that the relevant line may be in [kong-plugin-openwhisk/kong/plugins/openwhisk/handler.lua](https://github.com/Kong/kong-plugin-openwhisk/blob/master/kong/plugins/openwhisk/handler.lua)... with the line `local responses     = require "kong.tools.responses"`.  I'm not a lua developer... so, not in the best position to make a fix and submit a PR...

This [Changelog](https://github.com/Kong/kong/blob/master/CHANGELOG.md#plugins-3) shows the below statement regarding plugins (which is an indication of the issue) 

`The kong.tools.responses module was removed. Please use kong.response.exit from the PDK instead. You might want to use kong.log.err to log internal server errors as well.`

**Comment by devadvocado** [comment]
@treyau21 the fix has been merged in, but have yet to push out a new release (will go out shortly)
